var GAME_LEVELS = [
  // [
  //   "                      ",
  //   "                      ",
  //   "  x                x  ",
  //   "  x                x  ",
  //   "  x @      xxxxx  ox  ",
  //   "  xxxxx           ox  ",
  //   "      x    12345678x  ",
  //   "      xxxxxxxxxxxxxx  ",
  //   "                      "],
    // [
    //   "                      ",
    //   "                      ",
    //   "  x                x  ",
    //   "  x             x     ",
    //   "  x @      xxxxx   x  ",
    //   "  xxxxx            x  ",
    //   "      x   12 oox  ",
    //   "      xxxxxxxxxxxxxx  ",
    //   "                      "],
  ["                                                                                                            ",
   "                                                                                                            ",
   "                                                                                    o                       ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                               o            ",
   "                                                                                              sss           ",
   "                                                                               aa      xx    sssss          ",
   "  x                                                             o o      xx                   sss           ",
   "  x                 q                  w     q     w                                                        ",
   "  x                 q                  w     q     w          ssssss                                        ",
   "  x                 q      q           w     q     w                                                  wxxx  ",
   "  x                 q      q           w     q     w                                                  w  x  ",
   "  x      q          q   o  q   w       w     q     w                                                  w  x  ",
   "  x      q     1    q      q   w       w     q     w  xxxxx                                           wo x  ",
   "  x      q   xxxx   q   o  q   w       w     q     w                                                  w  x  ",
   "  x  @   q   x  x   q      q   w       w     q     w                                         xxxxx    w  x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxx  ",
   "                                  x 2 x                          x!!!!!x                                    ",
   "                                  xxxxx                          xxxxxxx                                    ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            "],
  ["          x                                                                                                   ",
   "          x                                                                                 y            x    ",
   "   @      x                                         u   r                                   y            x    ",
   "  xxxxx   x                                         u o r                                   y      x     x    ",
   "  x  q    x                                         u   r                               o   y      xx    x    ",
   "  x  q    x                                         u   r                          6        y      x x   x    ",
   "  x  q    x                       t                 u 4 r                         xxx       y      x  x  x    ",
   "  x  q    x                       t                xxxxxxxx                                 y  hh  x     x    ",
   "  x  q    x                       t                              o o      ggggg             y      x    xx    ",
   "  x  q    x     5                 t                                                         y      x   x x    ",
   "  x  q    x     x                 t        fffff               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x  x    ",
   "  x  q    x   xxxxx               t                      xxxxxxx o                      r         x  x   x    ",
   "  x  q  o x               o       t                      x                              r         x      x    ",
   "  x  q    e             hhhhh     t                  xxxxx         ggg                  r         xx     x    ",
   "  x  q o  e                       t                  x   i                              r         x x    x    ",
   "  x  q    e                       t              xxxxx   i                     8        r                x    ",
   "  x3 q  o e                       t              x  o o  i                     x        r                x    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                                      x   x                       xooooox                                     ",
   "                                      xkkkx                       xxxxxxx                                     ",
   "                                      x   x                                                                   ",
   "                                      x o x                                                                   ",
   "                                      x 7 x                                                                   ",
   "                                      xxxxx                                                                   "],

  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "         i u y t r e                                                                                              ",
   "         i u y t r e                                               xdddx                                          ",
   "         i u y t r e                                               x   x                                          ",
   "         i u y t r e                                               x   x                                       x  ",
   "         i u y t r e                                               xjjjx                                       x  ",
   "         i u y t r e                                              xx   xx                                      x  ",
   "      o  i u y t r e                                              xx 8 xx                           e   t      x  ",
   "      xxxx u y t r e                                           oo xxxxxxx                           e   t      x  ",
   "      x  x u y t r e                                           xtuxtututxutx                        e   t      x  ",
   "      x  xxxxxxxxxxxx                                         xt           tx                       e   t      x  ",
   "                         x     ddd                           xu             ux                      e   t      x  ",
   "                                      x    jjj               x                                    o e o t o 4  x  ",
   "                                                 x     hhh   x     o   o        ddddd               e   t   x  x  ",
   "                                                             x                           xxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                             x6    x   x                x                         ",
   "                                                             xx             xx          x                         ",
   "                                                                                                                  ",
   "                                              x                          x       xxx                              ",
   "                               e     e        x                          x                u                      x",
   "                               e     e        x                          x                u                      x",
   "                               e     e        x                          x         kkk    u                      x",
   "                               e     e        x                      5   x                u                      x",
   "                               e     e        x                      x   x                u                      x",
   "                   3           e     e        x             o  o     x   x              xxxxx                    x",
   "               xxxxxxx        xxxhhhxxx       x                      x   x                          o            x",
   "              xx     xx         x   x         x            xxxxxx    x   x                        fffff          x",
   "             xx       xx        x o x         x                      x   x                                       x",
   "            xx         x        x   x        xx     hh               x   x                                       x",
   "           xx          x    x   x   x         x                      x   xxxxxxx xxxxxx                          x",
   "   @      xx           x        x o x         x                      x o    t    x x                       kkk   x",
   "xxxxxxxxxxx            x        x   x         x      xxxxxxxxxxxxxxxxx      t    x x7                            x",
   "                       xxxxxxxxxx   xxxxxxxxxxxxxx   xxxxxxxxxx      xxxxxxxxxxxxx xx  o                         x",
   "                       xxxxxxx    o                 xxxxxxxxxx                      xx                           x",
   "                       xxxxxxx                     xxxxxxxxxx                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                       xxxxxxxx       xxxxxxxxxxxxxxxxxxxxxx                                                      ",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                       ",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                         "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
