var GAME_LEVELS = [

  ["                                                                                                            ",
   "                                                                                                            ",
   "                                                                                    o                       ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                               o            ",
   "                                                                                              sss           ",
   "                                                                               aa      xx    s!!!s          ",
   "  x                                                             o o      xx                   s!s           ",
   "  x                 q                  w     q     w                                           v            ",
   "  x                 q                  w     q     w          ssssss                                        ",
   "  x                 q      q           w     q     w                                                  wxxx  ",
   "  x                 q      q           w     q     w                                                  w  x  ",
   "  x      q          q   o  q   w       w     q     w                                                  w  x  ",
   "  x      q     1    q      q   w       w     q     w  xxxxx                                           wo x  ",
   "  x      q   xxxx   q   o  q   w       w     q     w                                                  w  x  ",
   "  x  @   q   x  x   q      q   w       w     q     w                                         xxxxx    w  x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxx  ",
   "                                  x 2 x                          x!!!!!x                                    ",
   "                                  xxxxx                          xxxxxxx                                    ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            "],
  ["          x!x                                                                                                 ",
   "          x!x                                                                               y            x    ",
   "   @      x!x                                       u   r                 o                 y            x    ",
   "  xxxxx   x!xxxxxxxxxxxx                            u   r                 o                 y      x     x    ",
   "  x       x!!!!!!!!!!!!x                            u   r               hhhhh           o   y      xx    x    ",
   "  x       xxxxxxxxxxxx!x                            u   r                          6        y      x x   x    ",
   "  x       x          x!x                            u 4 r                         xxx       y      x  x  x    ",
   "  x       x           v                            xxxxxxxx                                 y  jj  x     x    ",
   "  x       x                                                      o o                        y      x    xx    ",
   "  x       x     5                                                                           y      x   x x    ",
   "  x       x     x                 t            fff             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x  x    ",
   "  xxxq    x   xxxxx               t         ffff         xxxxxxx                        r         x  x   x    ",
   "  x  q  o x               o       t                      x o w                          r         x      x    ",
   "  x  q    e             hhhhh     t                  xxxxx   w                          r         xx     x    ",
   "  x  q o  e                       t   x   x          x   i   w                          r         x x    x    ",
   "  x  q    e                       t   x   x      xxxxx   i   w                 8        r                x    ",
   "  x3 q  o e                       t   x  xx      x    o  i   w                 x        r        =       x    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!xxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                                      x o xxxxxxxx                xooooox                                     ",
   "                                      x kkx                       xxxxxxx                                     ",
   "                                      x   x                                                                   ",
   "                                      x   x                                                                   ",
   "                                      x 7 x                                                                   ",
   "                                      xxxxx                                                                   "],

  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "         i u y t r e                                                                                              ",
   "         i u y t r e                                               x ddx                                          ",
   "         i u y t r e                                               x   x                                          ",
   "         i u y t r e                                               x   x                                       x  ",
   "         i u y t r e                                               x jjx                                       x  ",
   "         i u y t r e                                              xx   xx                                      x  ",
   "      o  i u y t r e                                              xx o xx                           e   t      x  ",
   "      xxxx u y t r e                                           oo xxxxxxx                           e   t      x  ",
   "      x!!x u y t r e                                           xtuxtututxutx                        e   t      x  ",
   "      x!!xxxxxxxxxxxx                                         xt=          tx                       e   t      x  ",
   "      x!!!!!!!!!!!!!!x   x     dd                            xu             ux                      e   t   o  x  ",
   "      xxxxxxxxxx!xvx!x               xx   jjj              n x                                    o e o t   o  x  ",
   "               x!xvxv                            xxx   hhh   x     o   o        ddddd               e   t   x  x  ",
   "                v                                            x                           xxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                             x     x   x                x                         ",
   "                                                             xxx   x   x    xx          x                         ",
   "                                                               xxx x                                              ",
   "                                              x                  xxx     x       xxx                              ",
   "                               e     e        x                          x                u                      x",
   "                               e     e        x                          x                u                      x",
   "                               e     e        x                          x         kk     u                      x",
   "                               e     e        x                          x                u                      x",
   "                               e     e        x                      x   x                u                      x",
   "                               e     e        x             o  o     x   x              xxxxx                    x",
   "               xxxxxxx        xxxhhhxxx       x                      x   x                          o            x",
   "              xx     xx         x   x         x            xxxxxx    x   x                        fffff          x",
   "             xx       xx        x o x         x                      x   x                                       x",
   "            xx         x        x   x        xx     hh               x   x                                       x",
   "           xx          x    x   x   x         x                      x   xxxxxxx xxxxxx                          x",
   "   @      xx           x        x o x!!!!!!!!!x                      x o    t    x!x                       xxx   x",
   "xxxxxxxxxxx            x!!!!!!!!x   x!!!!!!!!!x      xxxxxxxxxxxxx   x      t    x!x                             x",
   "                       xxxxxxxxxx   xxxxxxxxxxxxxx   xxxxxxxxxx      xxxxxxxxxxxxx!xx  o                         x",
   "                       xxxxxxx    o                 xxxxxxxxxx                    v xx                 = = =     x",
   "                       xxxxxxx                     xxxxxxxxxx                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                       xxxxxxxx       xxxxxxxxxxxxxxxxxxxxxx                                                      ",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
